export {
  RiAddLine as Plus,
  RiCloseLine as X,
  RiCodeLine as Code,
  RiDeleteBinLine as Trash,
  RiDownloadLine as Download,
  RiEditLine as Pencil,
  RiFileCopyLine as Copy,
  RiGithubFill as Github,
  RiMoreLine as MoreHorizontal,
  RiPushpinLine as Pin,
  RiSearchLine as Search,
  RiSendPlaneLine as Send,
  RiSparklingLine as Sparkles,
} from '@remixicon/react'
